spring:
  datasource:
    url: jdbc:h2:file:~/.h2/DBName;
    platform: h2
    username: ji
    password:
    driverClassName: org.h2.Driver
    data: classpath:sql/init.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  h2:
    console:
      enabled: on
      path: /console
      settings:
        trace: false
        web-allow-others: on

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
