INSERT INTO "PUBLIC"."ACCOUNT"("ID","INVITER","PASSWORD","USERNAME") VALUES (null, null, 'admin', 'admin');
INSERT INTO "PUBLIC"."ACCOUNT_ROLE"("USERNAME","ROLE") VALUES ('admin', 'admin');
INSERT INTO "PUBLIC"."ACCOUNT_ROLE"("USERNAME","ROLE") VALUES ('admin', 'user');