INSERT INTO "PUBLIC"."ACCOUNT"("ID","INVITER","PASSWORD","USERNAME") VALUES (null, null, admin, admin)
INSERT INTO "PUBLIC"."ACCOUNT_ROLE"("ID","ROLE") VALUES (0, admin)
INSERT INTO "PUBLIC"."ACCOUNT_ROLE"("ID","ROLE") VALUES (0, user)